general:
  # startup_commands: ['shell-exec zebar']

  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  config_reload_commands: []

  focus_follows_cursor: false

  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true

    trigger: 'monitor_focus'

  hide_method: 'cloak'

  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true

  inner_gap: '0px'

  outer_gap:
    top: '0px'
    right: '0px'
    bottom: '0px'
    left: '0px'

window_effects:
  focused_window:
    border:
      enabled: false
      color: '#FFFFFF'

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: true
      style: 'square'

  other_windows:
    border:
      enabled: false
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'

window_behavior:
  initial_state: 'tiling'

  state_defaults:
    floating:
      centered: true

      shown_on_top: false

    fullscreen:
      maximized: true

      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }

      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }


binding_modes:
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

# USING NUMLOCK DUE TO CUSTOM REMAP WITH VIA (RCTRL -> NUMLOCK)

keybindings:
  - commands: ['focus --direction left']
    bindings: ['f24+h', 'f24+left']
  - commands: ['focus --direction right']
    bindings: ['f24+l', 'f24+right']
  - commands: ['focus --direction up']
    bindings: ['f24+k', 'f24+up']
  - commands: ['focus --direction down']
    bindings: ['f24+j', 'f24+down']

  - commands: ['move --direction left']
    bindings: ['f24+shift+h', 'f24+shift+left']
  - commands: ['move --direction right']
    bindings: ['f24+shift+l', 'f24+shift+right']
  - commands: ['move --direction up']
    bindings: ['f24+shift+k', 'f24+shift+up']
  - commands: ['move --direction down']
    bindings: ['f24+shift+j', 'f24+shift+down']

  - commands: ['resize --width -2%']
    bindings: ['f24+u']
  - commands: ['resize --width +2%']
    bindings: ['f24+p']
  - commands: ['resize --height +2%']
    bindings: ['f24+o']
  - commands: ['resize --height -2%']
    bindings: ['f24+i']

  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['f24+r']

  - commands: ['wm-toggle-pause']
    bindings: ['f24+shift+p']

  - commands: ['toggle-tiling-direction']
    bindings: ['f24+v']

  - commands: ['wm-cycle-focus']
    bindings: ['f24+space']

  - commands: ['toggle-floating --centered']
    bindings: ['f24+shift+space']

  - commands: ['toggle-tiling']
    bindings: ['f24+t']

  - commands: ['toggle-fullscreen']
    bindings: ['f24+f']

  - commands: ['toggle-minimized']
    bindings: ['f24+m']

  - commands: ['close']
    bindings: ['f24+shift+q']

  - commands: ['wm-exit']
    bindings: ['f24+shift+e']

  - commands: ['wm-reload-config']
    bindings: ['f24+shift+r']

  - commands: ['wm-redraw']
    bindings: ['f24+shift+w']

  - commands: ['shell-exec cmd']
    bindings: ['f24+enter']

  - commands: ['focus --next-active-workspace']
    bindings: ['f24+s']
  - commands: ['focus --prev-active-workspace']
    bindings: ['f24+a']

  - commands: ['focus --recent-workspace']
    bindings: ['f24+d']

  - commands: ['focus --workspace 1']
    bindings: ['f24+1']
  - commands: ['focus --workspace 2']
    bindings: ['f24+2']
  - commands: ['focus --workspace 3']
    bindings: ['f24+3']
  - commands: ['focus --workspace 4']
    bindings: ['f24+4']
  - commands: ['focus --workspace 5']
    bindings: ['f24+5']
  - commands: ['focus --workspace 6']
    bindings: ['f24+6']
  - commands: ['focus --workspace 7']
    bindings: ['f24+7']
  - commands: ['focus --workspace 8']
    bindings: ['f24+8']
  - commands: ['focus --workspace 9']
    bindings: ['f24+9']

  - commands: ['move-workspace --direction left']
    bindings: ['f24+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['f24+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['f24+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['f24+shift+s']

  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['f24+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['f24+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['f24+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['f24+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['f24+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['f24+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['f24+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['f24+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['f24+shift+9']
